
name: Daily News

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"
    

  
env: 
  client_id: ${{ secrets.CLIENT_ID }}
  client_secret: ${{ secrets.CLIENT_SECRET }}
  email: ${{ secrets.EMAIL_ID }}
  phone_number: ${{ secrets.PHONE_NUMBER }}

jobs:
  scrape_headlines:     
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: actions/cache@v3
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hasFiles('requirements.txt') }}-test1
   
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: pip install -r requirements.txt
   
    - name: Run Scraper
      run: python main.py
     






